# Generated by Django 2.1.5 on 2019-04-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_subtext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subtext',
        ),
    ]
