# Generated by Django 2.1.5 on 2019-04-04 03:39

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test_text',
            field=markdownx.models.MarkdownxField(blank=True, verbose_name='test_text'),
        ),
    ]
