# Generated by Django 2.1.5 on 2019-04-04 04:19

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_test_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='key',
        ),
        migrations.AlterField(
            model_name='post',
            name='test_text',
            field=markdownx.models.MarkdownxField(verbose_name='test_text'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
