# Generated by Django 2.1.5 on 2019-04-04 15:58

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190404_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='test_text',
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=markdownx.models.MarkdownxField(verbose_name='test_text'),
        ),
    ]
